'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: cardboard.jsx by jimmie
 * Created: 2017-05-31 @ 15:16
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-31).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */


/**
 * DOING: Import react and associated libraries
 * here to separate from the rest of the code.
 */
import React from 'react';


/**
 * DOING: Import react components here
 * to separate from the rest of the code.
 */
import CardTile from './cardtile.jsx';


const CardBoard = props => {

    return (
        <div style={{display:'flex', flexWrap:'wrap', justifyContent:'space-around'}}>
            <CardTile key={1} />
            <CardTile key={2} />
            <CardTile key={3} />
            <CardTile key={4} />
            <CardTile key={5} />
            <CardTile key={6} />
            <CardTile key={7} />
            <CardTile key={8} />
            <CardTile key={9} />
            <CardTile key={10} />
            <CardTile key={11} />
            <CardTile key={12} />
            <CardTile key={13} />
            <CardTile key={14} />
            <CardTile key={15} />
        </div>
    )
};

export default CardBoard;