'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: connection-status-progress.jsx by jimmie
 * Created: 2017-05-16 @ 15:16
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-16).
 *
 * Repository link: http://jimmie@gitlab.localdomain/connectiontool/fix.git
 */

/**
 * DOING: Import react and associated libraries
 * here to separate from the rest of the code.
 */
import React from 'react';

/**
 * DOING: Import app associated and universal libraries
 * here to separate from the rest of the code.
 */
import { propsAreSet } from '../..//lib/common-state.js';
import {
    PROGRESS_LINEAR_ACTIVE_GREEN,
    PROGRESS_LINEAR_ACTIVE_RED,
    PROGRESS_LINEAR_PASSIVE_GREEN,
    PROGRESS_LINEAR_PASSIVE_RED
} from '../..//constants/common-ui.js';
import {
    SYSTEM_NETWORK_PROBE_TIMEOUT
} from '../..//constants/common-application.js';


/**
 * DOING: Import material ui and interface
 * here to separate from the rest of the code.
 */
import LinearProgress from 'material-ui/LinearProgress';


const ConnectionStatusProgress = props => {

    /**
     * CLARIFY: Props are checked for state value and colors
     * and background colors for the linear progress transition
     * are set. Colors are fetched from ui-common helpers.
     */
    let color = (
        propsAreSet(props.home) && props.home.online
    ) ?
        PROGRESS_LINEAR_ACTIVE_GREEN : PROGRESS_LINEAR_ACTIVE_RED;

    let background = (
        propsAreSet(props.home) && props.home.online
    ) ?
        {backgroundColor: PROGRESS_LINEAR_PASSIVE_GREEN} : {backgroundColor: PROGRESS_LINEAR_PASSIVE_RED};

    return (
        <div>
            <LinearProgress
                mode="indeterminate"
                color={color}
                style={background}
            />
        </div>
    )
};

export default ConnectionStatusProgress;