'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: memory
 * Filename: home.js by jimmie
 * Created: 2017-05-31 @ 14:54
 * Product of: Webstorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-31).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */


/**
 * DOING: Import react and associated libraries
 * here to separate from the rest of the code.
 */
import { createSelector } from 'reselect';

/**
 * DOING: State should be fetched prior
 * to executing the selector functions.
 * @param state
 */
export const getNetwork = state => state;


/**
 * DOING: Get the highest order of network objects
 * stored in the state.
 */
export const networkSelector = createSelector([ getNetwork ], (network) => network);

/**
 * DOING: Get the child network objects by
 * name stored in the state.
 */
export const networkByNameSelector = createSelector([ getNetwork ], (network) => network.byName);

/**
 * DOING: Get the child network objects by
 * id stored in the state.
 */
export const networkByIdSelector = createSelector([ getNetwork ], (network) => network.byId);