'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: home.js by jimmie
 * Created: 2017-05-12 @ 15:26
 * Product of: Diskovery
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-12).
 *
 * Repository link: http://10.10.10.200/connectiontool/fix.git
 */


/**
 * Import universal/associated libraries
 * here to separate from other code.
 */
import {
    GET_PRELOAD_STATE,
    GET_CONNECTION_STATUS_ITEM
} from '../constants/action-types/home.js';


export default (state = [], {type, payload} ) => {

    switch (type) {

        case GET_PRELOAD_STATE:
            return Object.assign({}, payload);

        case GET_CONNECTION_STATUS_ITEM:
            return [

            ];

        default:
            return state;

    }
};