'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: common-render.js by jimmie
 * Created: 2017-06-01 @ 15:16
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-06-01).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */


/**
 * DOING: Import react and associated libraries
 * here to separate from the rest of the code.
 */

/**
 * DOING: Should return a event listener
 * state. Performs necessary state changes to
 * elements defined on event change for handler.
 * @param selector
 * @param stateObjects
 */
export const listenToElementState = (selector, {...stateObjects}) => {};


/**
 * DOING: Should return a state transformation
 * of the DOM element. Adds class if class
 * exists to the given element.
 * @param element
 * @param stateAttributes
 */
export const addClickStateToElement = (element, {...stateAttributes}) => {
    console.log('inside addClickStateToElement', JSON.stringify(stateAttributes));
} ;