'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: common-async.js by jimmie
 * Created: 2017-05-17 @ 15:16
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-06-16).
 *
 * Repository link: http://jimmie@gitlab.localdomain/connectiontool/fix.git
 */


/**
 * DOING: Asynchronous promise chains
 * need to be resolved. Try a resolution for
 * a returned promise or catch the error.
 * @param fn
 * @param args
 */
export async function getPromise(fn, ...args) {
    try {
        return await fn(args);
    } catch (err) {
        return {
            error: err,
        };
    }
}