"use strict";

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: webpack.config.js by jimmie
 * Created: 2017-03-01 @ 20:52
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-03-01).
 *
 * Repository link: project/repository
 */

const webpack = require('webpack');

module.exports = {
    entry: {
        app: ['webpack/hot/dev-server', './js/client/src/components/main/entry.jsx'],
    },
    output: {
        path: '/public/built',
        filename: 'bundle.js',
        publicPath: 'http://localhost:8080/built/'
    },
    devServer: {
        contentBase: '/public',
        publicPath: 'http://localhost:8080/built/'
    },
    target : 'node',
    devtool : 'source-map',
    module: {
        noParse: [ /^socket.io-client$/ ],
        exprContextCritical : false,
        loaders: [
            { test: /\.jsx?/, loader: 'babel-loader', exclude: /node_modules/ },
            { test: /\.css$/, loader: 'style-loader!css-loader' },
            { test: /\.less$/, loader: 'style-loader!css-loader!less-loader'}
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
};