'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: memory
 * Filename: entry.js by jimmie
 * Created: 2017-05-31 @ 20:53
 * Product of: Webstorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-31).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */

/**
 * DOING: Only legacy/non-custom libraries
 * imported here.
 */
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import configureStore from '../../store/configure-store';
import { Router, Route, hashHistory } from 'react-router'; // hashHistory for electron
import * as boardActions from '../../actions/board';

/**
 * DOING: Import universal and associated libraries
 * here to separate from the rest of the code.
 */

/**
 * DOING: Only style/theme libraries
 * imported here.
 */
import '../../../pub/less/main.less';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';


/**
 * DOING: Adding components from our own sources
 */
import Board from '../../components/home/board.jsx';
import Menu from '../../components/core/menu.jsx';

/**
 *
 * CLARIFY: Set color palette for material
 * UI theme, predefined styles from
 * material-ui/styles/colors
 */

const muiTheme = getMuiTheme({
    fontFamily: 'Permanent Marker',
    palette: {
        accent1Color: "#C8E6C9",
        accent2Color: "#fff",
        primary1Color: "#ffffff",
        textColor: "rgba(0, 0, 0, 0.54)",
        secondaryTextColor: "rgba(0, 0, 0, 0.54)",
        alternateTextColor: "#6B6B6B",
        primary3Color: "#ec407a",
        primary2Color: "#000000",
        canvasColor: "#fff",
        borderColor: "#888",
        disabledColor: "rgba(0, 0, 0, 0.26)",
        pickerHeaderColor: "#F9FFD1",
        clockCircleColor: "#000000",
        shadowColor: "#000"
    }
});

const store = configureStore();
store.dispatch(boardActions.dataToBoard());

render (
    <Provider store={store}>
        <MuiThemeProvider muiTheme={muiTheme}>
            <Router history={hashHistory}>
                <Route component={Menu}>
                    <Route path="/" component={Board} />
                </Route>
            </Router>
        </MuiThemeProvider>
    </Provider>
    ,
    document.getElementById('react-anchor')
);