'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: entry.js by jimmie
 * Created: 2017-03-01 @ 20:53
 * Product of: Diskovery
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-03-01).
 *
 * Repository link: http://10.10.10.200/connectiontool/fix.git
 */

/**
 * DOING: Only legacy/non-custom libraries
 * imported here.
 */
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import configureStore from '../../store/configure-store';
import { populate } from '../../store/populate-state';
import { Router, Route, hashHistory } from 'react-router'; // hashHistory for electron

/**
 * DOING: Only style/theme libraries
 * imported here.
 */
import '../../../pub/less/main.less';
import {
    grey900,
    grey50,
    pink200,
    pink500,
    green50,
    darkWhite,
    lightWhite,
    fullWhite,
} from 'material-ui/styles/colors';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';


/**
 * DOING: Adding components from our own sources
 */
import Home from '../..//components/home/home.jsx';
import Menu from '../..//components/core/menu.jsx';

/**
 *
 * CLARIFY: Set color palette for material
 * UI theme, predefined styles from
 * material-ui/styles/colors
 */

const muiTheme = getMuiTheme({
    fontFamily: 'Open Sans',
    palette: {
        accent1Color: "#C8E6C9",
        accent2Color: "#fff",
        primary1Color: "#ffffff",
        textColor: "rgba(0, 0, 0, 0.54)",
        secondaryTextColor: "rgba(0, 0, 0, 0.54)",
        alternateTextColor: "#6B6B6B",
        primary3Color: "#ec407a",
        primary2Color: "#000000",
        canvasColor: "#fff",
        borderColor: "#888",
        disabledColor: "rgba(0, 0, 0, 0.26)",
        pickerHeaderColor: "#F9FFD1",
        clockCircleColor: "#000000",
        shadowColor: "#000"
    }
});

/*
const muiTheme = getMuiTheme({
    palette: {
        primary1Color: fullWhite,
        primary2Color: green50,
        primary3Color: pink200,
        accent1Color: grey50,
        accent2Color: lightWhite,
        accent3Color: grey900,
        textColor: grey900,
        alternateTextColor: grey900,
        pickerHeaderColor: lightWhite,
    },
});
*/
const store = configureStore(populate.default());

render (
    <Provider store={store}>
        <MuiThemeProvider muiTheme={muiTheme}>
            <Router history={hashHistory}>
                <Route component={Menu}>
                    <Route path="/" component={Home} />
                </Route>
            </Router>
        </MuiThemeProvider>
    </Provider>
    ,
    document.getElementById('react-anchor')
);