'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: memory
 * Filename: game-dialog.jsx by jimmie
 * Created: 2017-05-31 @ 15:16
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-31).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */

/**
 * DOING: Import react and associated libraries
 * here to separate from the rest of the code.
 */
import React from 'react';


/**
 * DOING: Import app associated and universal libraries
 * here to separate from the rest of the code
 */


/**
 * DOING: Import material ui and interface
 * here to separate from the rest of the code.
 */
import Dialog from 'material-ui/Dialog';


const GameDialog = props => {


    const titleGame = `Congratulations! Level ${props.activeGame} finished!`;
    const bodyGame = `${props.score} points! Get ready for your next game....`;

    const titleFinal = `Game Over! Level ${props.activeGame} of ${props.totalGames} finished!`;
    const bodyFinal = `Its a win. You scored ${props.score} points!`;

    return (
        <div>
            <Dialog
                title={(props.final) ? titleFinal : titleGame}
                modal={true}
                open={props.open}
                titleStyle={{fontFamily: 'Bangers', fontSize: '28px', color: '#45B649', textAlign: 'Center'}}
                bodyStyle={{fontFamily: 'Bangers', fontSize: '22px', textAlign: 'Center'}}
            >
                {(props.final) ? bodyFinal : bodyGame}
            </Dialog>
        </div>
    )
};


export default GameDialog;