'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: memory
 * Filename: populate-state.js by jimmie
 * Created: 2017-05-31 @ 20:53
 * Product of: Webstorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-31).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */


/**
 * DOING: Should return a predefined
 * state for its purpose to populate
 * the initialState.
 */
export const populate = {

    /**
     * CLARIFY: Default state sets initial
     * load, production defaults.
     * @returns {object}
     */
    default : () => {
        return {
            board : {
                score: 0,
                flipCount : 0,
                sessions: {
                    session1 : {
                        timestamp : '2017-06-31 7:22pm',
                        score : 24,
                    },
                    session2 : {
                        timestamp : '2017-06-22 7:22pm',
                        score : 18,
                    },
                    session3 : {
                        timestamp : '2017-06-15 7:22pm',
                        score : 40,
                    },
                },
                byId : {
                    tile1 : {
                        name : "Abba doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 1,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile2 : {
                        name : "John doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 2,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile3 : {
                        name : "Ellie doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 3,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile4 : {
                        name : "Donnie doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 4,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile5 : {
                        name : "Betty doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 1,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile6 : {
                        name : "Kobal doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 6,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile7 : {
                        name : "Ronni doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 7,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile8 : {
                        name : "Bobba doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 8,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile9 : {
                        name : "Annie doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 9,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile10 : {
                        name : "Kavinsky doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 10,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile11 : {
                        name : "Gogo doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 11,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile12 : {
                        name : "Mimi doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 12,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile13 : {
                        name : "Acid doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 13,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile14 : {
                        name : "Terry doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 14,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                    tile15 : {
                        name : "Gunner doe",
                        imagePortraitUrl : '//url/to/portrait',
                        index : 15,
                        filename : 'portrait',
                        flipped : false,
                        matched : false,
                    },
                }
            },
        };
    },

};