'use strict';

/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: memory
 * Filename: populate-state.js by jimmie
 * Created: 2017-05-31 @ 20:53
 * Product of: Webstorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-05-31).
 *
 * Repository link: https://github.com/jimmiehansson/memory.git
 */


/**
 * DOING: Should return a predefined
 * state for its purpose to populate
 * the initialState.
 */
export const populate = {


    /**
     * CLARIFY: Default state sets initial
     * load, production defaults.
     * @returns {object}
     */
    default: () => {

        return {
            board: {
                score: 0,
                flipCount: 0,
                sessions: {
                    session1: {
                        timestamp: '2017-06-31 7:22pm',
                        score: 24,
                        tiles: {
                            tile1: {
                                name: "Jan doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 1,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile2: {
                                name: "Debbie doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 2,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile3: {
                                name: "Gunner doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 3,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile4: {
                                name: "Ali doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 4,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile5: {
                                name: "Donna doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 5,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile6: {
                                name: "Abba doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 6,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile7: {
                                name: "Debbie doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 7,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile8: {
                                name: "Gunner doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 8,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile9: {
                                name: "Ali doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 9,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                            tile10: {
                                name: "Donna doe",
                                imagePortraitUrl: '//url/to/portrait',
                                index: 4,
                                filename: 'portrait',
                                flipped: false,
                                matched: false,
                                pending: false,
                            },
                        }
                    },
                    session2: {
                        timestamp: '2017-06-22 7:22pm',
                        score: 18,
                    },
                    session3: {
                        timestamp: '2017-06-15 7:22pm',
                        score: 40,
                    },
                },
            },
        };
    },
};
