/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: app-info.jsx by jimmie
 * Created: 2017-03-14 @ 22:44
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-03-14).
 *
 * Repository link: http://jimmie@gitlab.localdomain/connectiontool/fix.git
 */

/**
 * DOING: Import react and associated libraries
 * here to separate from the rest of the code.
 */
import React from 'react';

/**
 * DOING: Import app associated and universal libraries
 * here to separate from the rest of the code.
 */
import { propsAreSet } from '../../lib/common-state';
import {
    APPLICATION_NAME,
    APPLICATION_VERSION,
    APPLICATION_RC,
    APPLICATION_RCTYPE,
} from '../../constants/common-application.js';


const AppInfo = props => {

    let name = (propsAreSet(props.home)) ? props.home.application.name : APPLICATION_NAME;
    let version = (propsAreSet(props.home)) ? props.home.application.version : APPLICATION_VERSION;
    let rc = (propsAreSet(props.home)) ? props.home.application.rc : APPLICATION_RC;
    let rcType = (propsAreSet(props.home)) ? props.home.application.rcType : APPLICATION_RCTYPE;

    return (
        <div>
            { name } v{ version } - ( {rcType} {rc})
        </div>
    )
};

export default AppInfo;