/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * GLOBAL FILE NOTATIONS
 * Project of: fix
 * Filename: home.component.jsx by jimmie
 * Created: 2017-03-09 @ 14:04
 * Product of: WebStorm
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by jimmie on (2017-03-09).
 *
 * Repository link: project/repository
 */

import React, { Component } from "react";
import { Link } from "react-router";
import Header from "./header.jsx";
import {Tabs, Tab} from "material-ui/Tabs";


class Menu extends Component {


    render() {
        return(
            <div>
                <Header />
                <Tabs>
                    <Tab
                        value="/"
                        label="Översikt"
                        containerElement={<Link to="/" />}
                    />
                    <Tab
                        value="/connection"
                        label="Uppkoppling"
                        containerElement={<Link to="/connection" />}
                    />
                    <Tab
                        value="/quality"
                        label="Kvalitet"
                        containerElement={<Link to="/quality" />}
                    />

                </Tabs>
                {this.props.children }
            </div>
        )
    }

}


export default Menu